//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSiteApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application_Table
    {
        public int Appl_ID { get; set; }
        public int Job_ID { get; set; }
        public int User_ID { get; set; }
        public string CV { get; set; }
        public System.DateTime Appl_Date { get; set; }
        public string Appl_Status { get; set; }
    }
}
