//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSiteApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Table
    {
        public int Comp_ID { get; set; }
        public string Comp_Name { get; set; }
        public string Comp_Address { get; set; }
        public long Comp_Phone { get; set; }
        public string Comp_Description { get; set; }
        public string WebsiteAddress { get; set; }
    }
}
