//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSiteApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Table
    {
        public int Job_ID { get; set; }
        public int Comp_ID { get; set; }
        public string Job_Title { get; set; }
        public string Job_Descr { get; set; }
        public string Location { get; set; }
        public int Salary { get; set; }
        public string Skills { get; set; }
        public string Experience { get; set; }
        public System.DateTime LastDate { get; set; }
        public string Job_Status { get; set; }
    }
}
