//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSiteApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class JobSiteDBEntities : DbContext
    {
        public JobSiteDBEntities()
            : base("name=JobSiteDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application_Table> Application_Table { get; set; }
        public virtual DbSet<Company_Table> Company_Table { get; set; }
        public virtual DbSet<Job_Table> Job_Table { get; set; }
        public virtual DbSet<Login_Table> Login_Table { get; set; }
        public virtual DbSet<User_Table> User_Table { get; set; }
    
        public virtual int sp_companyinsert(Nullable<int> cid, string cname, string caddr, Nullable<long> cphone, string cdesc, string cweb)
        {
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            var cnameParameter = cname != null ?
                new ObjectParameter("cname", cname) :
                new ObjectParameter("cname", typeof(string));
    
            var caddrParameter = caddr != null ?
                new ObjectParameter("caddr", caddr) :
                new ObjectParameter("caddr", typeof(string));
    
            var cphoneParameter = cphone.HasValue ?
                new ObjectParameter("cphone", cphone) :
                new ObjectParameter("cphone", typeof(long));
    
            var cdescParameter = cdesc != null ?
                new ObjectParameter("cdesc", cdesc) :
                new ObjectParameter("cdesc", typeof(string));
    
            var cwebParameter = cweb != null ?
                new ObjectParameter("cweb", cweb) :
                new ObjectParameter("cweb", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_companyinsert", cidParameter, cnameParameter, caddrParameter, cphoneParameter, cdescParameter, cwebParameter);
        }
    
        public virtual int sp_jobinsert(Nullable<int> cid, string jobtitle, string jobdesc, string loc, Nullable<int> salary, string skills, string exp, Nullable<System.DateTime> last_date, string jobst)
        {
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            var jobtitleParameter = jobtitle != null ?
                new ObjectParameter("jobtitle", jobtitle) :
                new ObjectParameter("jobtitle", typeof(string));
    
            var jobdescParameter = jobdesc != null ?
                new ObjectParameter("jobdesc", jobdesc) :
                new ObjectParameter("jobdesc", typeof(string));
    
            var locParameter = loc != null ?
                new ObjectParameter("loc", loc) :
                new ObjectParameter("loc", typeof(string));
    
            var salaryParameter = salary.HasValue ?
                new ObjectParameter("salary", salary) :
                new ObjectParameter("salary", typeof(int));
    
            var skillsParameter = skills != null ?
                new ObjectParameter("skills", skills) :
                new ObjectParameter("skills", typeof(string));
    
            var expParameter = exp != null ?
                new ObjectParameter("exp", exp) :
                new ObjectParameter("exp", typeof(string));
    
            var last_dateParameter = last_date.HasValue ?
                new ObjectParameter("last_date", last_date) :
                new ObjectParameter("last_date", typeof(System.DateTime));
    
            var jobstParameter = jobst != null ?
                new ObjectParameter("jobst", jobst) :
                new ObjectParameter("jobst", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_jobinsert", cidParameter, jobtitleParameter, jobdescParameter, locParameter, salaryParameter, skillsParameter, expParameter, last_dateParameter, jobstParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_loginidcountget(string una, string pswd)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pswdParameter = pswd != null ?
                new ObjectParameter("pswd", pswd) :
                new ObjectParameter("pswd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_loginidcountget", unaParameter, pswdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_loginidmax()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_loginidmax");
        }
    
        public virtual int sp_loginsert(Nullable<int> rid, string una, string pswd, string logty)
        {
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(int));
    
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pswdParameter = pswd != null ?
                new ObjectParameter("pswd", pswd) :
                new ObjectParameter("pswd", typeof(string));
    
            var logtyParameter = logty != null ?
                new ObjectParameter("logty", logty) :
                new ObjectParameter("logty", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_loginsert", ridParameter, unaParameter, pswdParameter, logtyParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_selectlogid(string una, string pswd)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pswdParameter = pswd != null ?
                new ObjectParameter("pswd", pswd) :
                new ObjectParameter("pswd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_selectlogid", unaParameter, pswdParameter);
        }
    
        public virtual ObjectResult<string> sp_selectusertype(string una, string pswd)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pswdParameter = pswd != null ?
                new ObjectParameter("pswd", pswd) :
                new ObjectParameter("pswd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_selectusertype", unaParameter, pswdParameter);
        }
    
        public virtual int sp_userinsert(Nullable<int> uid, string una, Nullable<int> age, string addr, string email, Nullable<long> phone, string gender, string qual, string skills, string exp)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("age", age) :
                new ObjectParameter("age", typeof(int));
    
            var addrParameter = addr != null ?
                new ObjectParameter("addr", addr) :
                new ObjectParameter("addr", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var phoneParameter = phone.HasValue ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(long));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var qualParameter = qual != null ?
                new ObjectParameter("qual", qual) :
                new ObjectParameter("qual", typeof(string));
    
            var skillsParameter = skills != null ?
                new ObjectParameter("skills", skills) :
                new ObjectParameter("skills", typeof(string));
    
            var expParameter = exp != null ?
                new ObjectParameter("exp", exp) :
                new ObjectParameter("exp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_userinsert", uidParameter, unaParameter, ageParameter, addrParameter, emailParameter, phoneParameter, genderParameter, qualParameter, skillsParameter, expParameter);
        }
    
        public virtual int sp_JobSearch(string qry)
        {
            var qryParameter = qry != null ?
                new ObjectParameter("qry", qry) :
                new ObjectParameter("qry", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_JobSearch", qryParameter);
        }
    
        public virtual int sp_InsertApplication(Nullable<int> jid, Nullable<int> uid, string cv, Nullable<System.DateTime> dat, string sta)
        {
            var jidParameter = jid.HasValue ?
                new ObjectParameter("jid", jid) :
                new ObjectParameter("jid", typeof(int));
    
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var cvParameter = cv != null ?
                new ObjectParameter("cv", cv) :
                new ObjectParameter("cv", typeof(string));
    
            var datParameter = dat.HasValue ?
                new ObjectParameter("dat", dat) :
                new ObjectParameter("dat", typeof(System.DateTime));
    
            var staParameter = sta != null ?
                new ObjectParameter("sta", sta) :
                new ObjectParameter("sta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertApplication", jidParameter, uidParameter, cvParameter, datParameter, staParameter);
        }
    
        public virtual ObjectResult<string> sp_CheckAlreadyApplied(Nullable<int> jid, Nullable<int> uid)
        {
            var jidParameter = jid.HasValue ?
                new ObjectParameter("jid", jid) :
                new ObjectParameter("jid", typeof(int));
    
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_CheckAlreadyApplied", jidParameter, uidParameter);
        }
    }
}
